---

grafana_release: "5.4.2-1"


grafana_package: "grafana-{{ grafana_release }}.x86_64.rpm"
grafana_url: "https://dl.grafana.com/oss/release/{{ grafana_package }}"

grafana_port: 3000
grafana_uid: 999
grafana_gid: 997

grafana_conf_dir: "/etc/grafana/"
grafana_dashboard_dir: "/etc/grafana/provisioning/dashboards/"

prometheus_server: http://prometheus:9090

prometheus_redeploy: False
prometheus_port: 9090
prometheus_ds_name: Prometheus
prometheus_node_exporter_job_name: host-metrics
