---

- name: install docker py
  yum:
    name: docker-python
    state: latest

- name: download and run registrator
  docker_container:
    name: registratorMaster
    image: "{{ registrator_image }}"
    volumes:
      - "{{ registrator_docker_socket }}:/tmp/docker.sock"
    state: started
    command: -internal {{ registrator_uri }}
