---

- name: Install dependent python modules
  pip:
    name: "{{item}}"
    state: present
  with_items:
    - google-common
    - protobuf 

- name: install docker py
  pip:
    name: docker-compose
    version: 1.9.0

- name: install docker py
  pip:
    name: docker-py

- name: download and run registrator
  docker_container:
    name: registratorMaster
    image: "{{ registrator_image }}"
    pull: true
    restart_policy: always
    volumes:
      - "{{ registrator_docker_socket }}:/tmp/docker.sock"
    state: started
    command: -resync 10 -internal {{ registrator_uri }}
