---

docker_registry:
  - url: "dockereq:5000"
  - url: "dockereq1:5000"

docker_options: ""

docker_version_deb: "docker-ce"
docker_version_rpm: "docker-ce"

docker_data_root: "/var/lib/docker"

docker: false
restart: false  
update: false  

eth_if: "eth0"  
ansible_eth_if: "ansible_{{ eth_if }}"

