---

- name: download and run rexray s3fs plugin
  shell: "docker plugin install --grant-all-permissions {{ rexray_image_s3fs }} S3FS_ACCESSKEY={{ s3_access_key }} S3FS_SECRETKEY={{ s3_secret_key }} S3FS_REGION={{ s3_region }} S3FS_ENDPOINT=https://{{ s3_region_endpoint }} S3FS_OPTIONS=\"allow_other,use_path_request_style,nonempty,url=https://{{ s3_region_endpoint }}\""
  ignore_errors: true

- name: reconfigure s3fs plugin
  shell: "docker plugin set {{ rexray_image_s3fs }} S3FS_ACCESSKEY={{ s3_access_key }} S3FS_SECRETKEY={{ s3_secret_key }} S3FS_REGION={{ s3_region }} S3FS_ENDPOINT=https://{{ s3_region_endpoint }} S3FS_OPTIONS=\"allow_other,use_path_request_style,nonempty,url=https://{{ s3_region_endpoint }}\""
