
- name: copy aventer repo
  copy:
    src: aventer-rel.repo
    dest: /etc/yum.repos.d/aventer-rel.repo
    mode: 0640
  when:
    ansible_os_family == "RedHat"

- name: add aventer gpg-key
  copy: 
    src: support_aventer.asc
    dest: /tmp/support_aventer.asc
  when:
    ansible_os_family == "Debian"

- name: add aventer repo file
  template: 
    src: aventer.list.j2
    dest:  /etc/apt/sources.list.d/aventer.list
    mode: 0644
  when:
    ansible_os_family == "Debian"


