---
- name: download metronome
  get_url:
    url: "{{ metronome_download_url }}"
    dest: /tmp/metronome.tgz
    mode: '0755'
    force: yes

- name: extract metronome archive
  unarchive:
    src: /tmp/metronome.tgz
    dest: /opt/mesosphere/
    remote_src: yes

- name: symlink metronome metronome 
  file: 
    src: /opt/mesosphere/metronome-{{ metronome_version }}
    dest: /opt/mesosphere/metronome
    state: link
    force: true

- name: create metronome group
  group:
    name: av_metronome
    system: yes
    state: present

- name: create metronome user
  user:
    name: av_metronome
    group: av_metronome
    groups: marathon
    create_home: no
    system: yes
    state: present    

- name: Recursively change ownership of a directory
  file:
    path: /opt/mesosphere/metronome
    state: directory
    recurse: yes
    owner: av_metronome
    group: av_metronome

- name: Delete old metronome config
  file: path=/etc/sysconfig/metronome state=absent

- name: configure metronome zookeeper
  lineinfile: dest=/etc/sysconfig/metronome create=yes state=present regexp="^METRONOME_ZK_URL=" line="METRONOME_ZK_URL=zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/metronome"

- name: configure mesos master nodes to metronome
  lineinfile: dest=/etc/sysconfig/metronome create=yes state=present regexp="^METRONOME_MESOS_MASTER_URL=" line="METRONOME_MESOS_MASTER_URL=zk://{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: set metronome role to metronome
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_ROLE=marathon" create=yes
  
- name: enable mesos authenticaton to metronome
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_AUTHENTICATION_ENABLED=true" create=yes

- name: enable mesos principal to metronome
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_AUTHENTICATION_PRINCIPAL={{ mesos_user }}" create=yes

- name: enable mesos secret file to metronome
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_AUTHENTICATION_SECRET_FILE=/etc/mesos/marathon.secret" create=yes

- name: enable mesos leader url with ssl
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_LEADER_UI_URL=https://leader.mesos:5050" create=yes
  when:
    - libprocess_enable_ssl == "true"

- name: enable mesos leader url without ssl
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_LEADER_UI_URL=http://leader.mesos:5050" create=yes
  when:
    - libprocess_enable_ssl == "false"

- name: add http port
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_PLAY_SERVER_HTTP_PORT=9000" create=yes

- name: add http port
  lineinfile: dest=/etc/sysconfig/metronome state=present line="" create=yes

- name: add metronome mesos user
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_USER=root" create=yes

- name: add libprocess port
  lineinfile: dest=/etc/sysconfig/metronome state=present line="LIBPROCESS_PORT=15201" create=yes

- name: add metronome confirm timeout
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_SCHEDULER_TASK_LAUNCH_CONFIRM_TIMEOUT=600000" create=yes

- name: add metronome launch timeout
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_SCHEDULER_TASK_LAUNCH_TIMEOUT=600000" create=yes

- name: enable ssl for mesos libprocess
  lineinfile: dest=/etc/sysconfig/metronome create=yes state=present regexp="^LIBPROCESS_SSL_ENABLED=*" line="LIBPROCESS_SSL_ENABLED={{ libprocess_enable_ssl }}"  

- name: enable ssl verify for mesos libprocess
  lineinfile: dest=/etc/sysconfig/metronome create=yes state=present regexp="^LIBPROCESS_SSL_VERIFY_CERT=*" line="LIBPROCESS_SSL_VERIFY_CERT={{ libprocess_enable_ssl_verify }}"  

- name: add mesos libprocess ssl key file
  lineinfile: dest=/etc/sysconfig/metronome create=yes state=present regexp="^LIBPROCESS_SSL_KEY_FILE=*" line="LIBPROCESS_SSL_KEY_FILE=/etc/mesos/ssl/mesos.key" 

- name: add mesos libprocess ssl cert file
  lineinfile: dest=/etc/sysconfig/metronome create=yes state=present regexp="^LIBPROCESS_SSL_CERT_FILE=*" line="LIBPROCESS_SSL_CERT_FILE=/etc/mesos/ssl/mesos.crt" 

- name: enable required ssl cert
  lineinfile: dest=/etc/sysconfig/metronome create=yes state=present regexp="^LIBPROCESS_SSL_REQUIRE_CERT=*" line="LIBPROCESS_SSL_REQUIRE_CERT={{ libprocess_ssl_require_cert }}" 

- name: copy metronome systemd 
  copy: 
    src: metronome.systemd 
    dest: /etc/systemd/system/metronome.service 
    mode: 0644  

- name: reload systemd
  command: systemctl daemon-reload

- name: start metronome
  service:
    name: "metronome"
    enabled: yes
    state: restarted
