---
- name: download mesos-dns
  get_url:
    url: "{{ metronome_download_url }}"
    dest: /tmp/metronome.tgz
    mode: '0755'
    force: yes

- name: extract metronome archive
  unarchive:
    src: /tmp/metronome.tgz
    dest: /opt/mesosphere/
    remote_src: yes

- name: symlink metronome metronome 
  file: 
    src: /opt/mesosphere/metronome-{{ metronome_version }}
    dest: /opt/mesosphere/metronome
    state: link

- name: Delete old metronome config
  file: path=/etc/sysconfig/metronome state=absent

- name: configure mesos master nodes
  lineinfile: dest=/etc/sysconfig/metronome create=yes state=present regexp="^METRONOME_ZK_URL=" line="METRONOME_ZK_URL=zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/metronome"

- name: configure mesos master nodes
  lineinfile: dest=/etc/sysconfig/metronome create=yes state=present regexp="^METRONOME_MESOS_MASTER_URL=" line="METRONOME_MESOS_MASTER_URL=zk://{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: set hostname in marathon
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_ROLE=marathon" create=yes
  
- name: enable mesos authenticaton
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_AUTHENTICATION_ENABLED=true" create=yes

- name: enable mesos principal
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_AUTHENTICATION_PRINCIPAL={{ mesos_user }}" create=yes

- name: enable mesos secret file
  lineinfile: dest=/etc/sysconfig/metronome state=present line="METRONOME_MESOS_AUTHENTICATION_SECRET_FILE=/etc/mesos/marathon.secret" create=yes

- name: create metronome group
  group:
    name: av_metronome
    system: yes
    state: present

- name: create metronome user
  user:
    name: av_metronome
    group: av_metronome
    create_home: no
    system: yes
    state: present

- name: copy metronome systemd 
  copy: 
    src: metronome.systemd 
    dest: /etc/systemd/system/metronome.service 
    mode: 0644  

- name: reload systemd
  command: systemctl daemon-reload

- name: start metronome
  service:
    name: "metronome"
    enabled: yes
    state: restarted
