---

- name: install mesos slave packages
  yum:
    name:
      - mesos-1.8.0
    state: installed
    
- name: disable mesos update
  lineinfile:
    dest=/etc/yum.conf
    line="{{ item.line }}"
    insertafter='EOF'
  with_items:
    - { line: 'exclude=mesos-*' }  

- name: Remove deprecated config files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/mesos-slave/modules"

- name: create zk file
  file: 
    path: /etc/mesos/zk 
    state: touch
    mode: 0640

- name: create ssl directory
  file: 
    path: /etc/mesos/ssl
    state: directory
    mode: 0750

- name: copy ssl cert
  copy:
    src: mesos.crt
    dest: /etc/mesos/ssl/mesos.crt
    mode: 0640

- name: copy ssl key
  copy:
    src: mesos.key
    dest: /etc/mesos/ssl/mesos.key
    mode: 0640

- name: configure zk access
  lineinfile: dest=/etc/mesos/zk create=yes state=present regexp="^zk=*" line="zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: configure mesos-zk string
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^MESOS_ZK=*" line="MESOS_ZK=file:///etc/mesos/zk"  

- name: configure user env string
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^USER=*" line="USER=root"  

- name: enable ssl for mesos libprocess
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_ENABLED=*" line="LIBPROCESS_SSL_ENABLED={{ libprocess_enable_ssl }}"

- name: enable ssl verify for mesos
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_VERIFY_CERT=*" line="LIBPROCESS_SSL_VERIFY_CERT={{ libprocess_enable_ssl_verify }}" 

- name: add mesos libprocess ssl key file
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_KEY_FILE=*" line="LIBPROCESS_SSL_KEY_FILE=/etc/mesos/ssl/mesos.key" 

- name: add mesos libprocess ssl cert file
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_CERT_FILE=*" line="LIBPROCESS_SSL_CERT_FILE=/etc/mesos/ssl/mesos.crt" 

- name: set hostname in mesos
  lineinfile: dest=/etc/mesos-slave/hostname state=present regexp="^" line="{{ inventory_hostname }}" create=yes

- name: increase the mesos-slave executor timeout
  lineinfile: dest=/etc/mesos-slave/executor_registration_timeout state=present line="5mins" regexp="^" create=yes

- name: add containerizer to the mesos-slave
  lineinfile: dest=/etc/mesos-slave/containerizers state=present line="docker,mesos" regexp="^" create=yes  

- name: add mesos-slave credentials
  lineinfile: dest=/etc/mesos-slave/credential state=present line="/etc/mesos/credential" regexp="^" create=yes  

- name: add mesos-slave http credentials
  lineinfile: dest=/etc/mesos-slave/http_credentials state=present line="/etc/mesos/http_credentials" regexp="^" create=yes  

- name: enable cluster http readonly authentication
  lineinfile: dest=/etc/mesos-slave/authenticate_http_readonly state=present create=yes regexp="^" line="true"  

- name: enable cluster http readwrite authentication
  lineinfile: dest=/etc/mesos-slave/authenticate_http_readwrite state=present create=yes regexp="^" line="true"  

- name: enable cluster http authenticators
  lineinfile: dest=/etc/mesos-slave/http_authenticators state=present create=yes regexp="^" line="basic"  

- name: add weave.socks to the mesos-slave
  lineinfile: dest=/etc/mesos-slave/docker_socket state=present line="/var/run/weave/weave.sock" regexp="^" create=yes  

- name: set slave ip in mesos
  lineinfile: dest=/etc/mesos-slave/ip state=present create=yes regexp="^" line="{{ ansible_default_ipv4.address }}"

- name: disable hostname lookup
  lineinfile: dest=/etc/mesos-slave/hostname_lookup state=present create=yes regexp="^" line="false"

- name: set memory profiling
  lineinfile: dest=/etc/mesos-slave/memory_profiling state=present create=yes regexp="^" line="true"

- name: set mesos isolation
  lineinfile: dest=/etc/mesos-slave/isolation state=present create=yes regexp="^" line="cgroups/all,disk/du,network/cni,filesystem/linux,docker/runtime,volume/sandbox_path,volume/secret,posix/rlimits,namespaces/pid,linux/capabilities,linux/seccomp"

- name: set image provider
  lineinfile: dest=/etc/mesos-slave/image_providers state=present create=yes regexp="^" line="appc,docker"

- name: set mesos module directory
  lineinfile: dest=/etc/mesos-slave/modules_dir state=present create=yes regexp="^" line="/etc/mesos/modules"

- name: set mesos seccomp directory
  lineinfile: dest=/etc/mesos-slave/seccomp_config_dir state=present create=yes regexp="^" line="/etc/mesos/seccomp"

- name: set mesos seccomp directory
  lineinfile: dest=/etc/mesos-slave/seccomp_profile_name state=present create=yes regexp="^" line="default.json"

- name: create mesos module directory
  file:
    path: /etc/mesos/modules
    state: directory
    mode: 0750    

- name: create mesos seccomp directory
  file:
    path: /etc/mesos/seccomp
    state: directory
    mode: 0750    

- name: copy mesos seccomp default profile
  copy:
    src: default.json
    dest: /etc/mesos/seccomp/default.json
    mode: 0640

- name: copy mesos credential
  template: src=credential.j2 dest=/etc/mesos/credential mode=0640  

- name: copy mesos http credential
  template: src=http_credentials.j2 dest=/etc/mesos/http_credentials mode=0640  

- name: ensure mesos-slave service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - mesos-slave

- name: ensure mesos-master service is disabled
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - mesos-master
