---

- name: install mesos slave packages
  yum:
    name:
      - mesos-1.8.0
    state: installed

- name: disable mesos update
  lineinfile:
    dest=/etc/yum.conf
    line="{{ item.line }}"
    insertafter='EOF'
  with_items:
    - { line: 'exclude=mesos-*' }

- name: copy modules config
  copy: 
    src: modules.config 
    dest: /etc/mesos-slave/modules 
    mode: 0755    

- name: Delete old zk entry
  file: path=/etc/mesos/zk state=absent

- name: configure zk access
  lineinfile: dest=/etc/mesos/zk create=yes state=present regexp="^zk" line="zk://{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: set hostname in mesos
  lineinfile: dest=/etc/mesos-slave/hostname state=present regexp="^" line="{{ inventory_hostname }}" create=yes

- name: increase the mesos-slave executor timeout
  lineinfile: dest=/etc/mesos-slave/executor_registration_timeout state=present line="5mins" create=yes

- name: add containerizer to the mesos-slave
  lineinfile: dest=/etc/mesos-slave/containerizers state=present line="docker,mesos" create=yes  

- name: add mesos-slave credentials
  lineinfile: dest=/etc/mesos-slave/credential state=present line="/etc/mesos/credential" create=yes  

- name: add mesos-slave http credentials
  lineinfile: dest=/etc/mesos-slave/http_credentials state=present line="/etc/mesos/credential" create=yes  

- name: enable cluster http readonly authentication
  lineinfile: dest=/etc/mesos-master/authenticate_http_readonly state=present create=yes regexp="^" line="true"  

- name: enable cluster http readwrite authentication
  lineinfile: dest=/etc/mesos-master/authenticate_http_readwrite state=present create=yes regexp="^" line="true"  

- name: enable cluster http authenticators
  lineinfile: dest=/etc/mesos-master/http_authenticators state=present create=yes regexp="^" line="basic"  

- name: add weave.socks to the mesos-slave
  lineinfile: dest=/etc/mesos-slave/docker_socket state=present line="/var/run/weave/weave.sock" create=yes  

- name: set slave ip in mesos
  lineinfile: dest=/etc/mesos-slave/ip state=present create=yes regexp="^" line="{{ ansible_default_ipv4.address }}"

- name: disable hostname lookup
  lineinfile: dest=/etc/mesos-slave/hostname_lookup state=present create=yes regexp="^" line="false"

- name: set memory profiling
  lineinfile: dest=/etc/mesos-slave/memory_profiling state=present create=yes regexp="^" line="true"

- name: set mesos isolation
  lineinfile: dest=/etc/mesos-slave/isolation state=present create=yes regexp="^" line="cgroups/all,disk/du,network/cni,filesystem/linux,docker/runtime,volume/sandbox_path,volume/secret,posix/rlimits,namespaces/pid,linux/capabilities"

- name: copy mesos credential
  template: src=credential.j2 dest=/etc/mesos/credential mode=0640  

- name: ensure mesos-slave service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - mesos-slave

- name: ensure mesos-master service is disabled
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - mesos-master
