---

- name: install mesos repo
  yum:
    name: http://repos.mesosphere.io/el/7/noarch/RPMS/{{ mesosphere_repo }}
    state: present

- name: install mesos slave packages
  yum: name={{ item }} state=latest
  with_items:
    - mesos

- name: disable mesos update
  lineinfile:
    dest=/etc/yum.conf
    line="{{ item.line }}"
    insertafter='EOF'
  with_items:
    - { line: 'exclude=mesos-*' }

- name: Delete old zk entry
  file: path=/etc/mesos/zk state=absent

- name: configure zk access
  lineinfile: dest=/etc/mesos/zk create=yes state=present regexp="^zk" line="zk://{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: set hostname in mesos
  lineinfile: dest=/etc/mesos-slave/hostname state=present regexp="^" line="{{ inventory_hostname }}" create=yes

- name: increase the mesos-slave executor timeout
  lineinfile: dest=/etc/mesos-slave/executor_registration_timeout state=present line="5mins" create=yes

- name: add containerizer to the mesos-slave
  lineinfile: dest=/etc/mesos-slave/containerizers state=present line="docker,mesos" create=yes  

- name: add mesos-slave credentials
  lineinfile: dest=/etc/mesos-slave/credential state=present line="/etc/mesos/credential" create=yes  

- name: add weave.socks to the mesos-slave
  lineinfile: dest=/etc/mesos-slave/docker_socket state=present line="/var/run/weave/weave.sock" create=yes  

- name: set slave ip in mesos
  lineinfile: dest=/etc/mesos-slave/ip state=present create=yes regexp="^" line="{{ ansible_default_ipv4.address }}"

- name: copy mesos credential
  template: src=credential.j2 dest=/etc/mesos/credential mode=0640  

- name: ensure mesos-slave service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - mesos-slave
