---
  - name: install chrony
    package:
      name: chrony
      state: latest
      update_cache: yes

  - name: test chrony running
    service:
      name: chronyd
      enabled: yes
      state: started
