---

- name: install packages centos
  yum:
    name:
      - curl
      - s3fs-fuse
      - rexray-0.11.4+2+dirty
    state: latest
    update_cache: yes

- name: copy rexray config
  template: src=rexray-config.yml.j2 dest=/etc/rexray/config.yml mode=0644
  
- name: copy rexray systemd scripts into place
  copy: src={{ item }} dest=/etc/systemd/system mode=0755
  with_items:
    - rexray.service

- name: reload systemd
  command: systemctl daemon-reload
  
- name: start rexray
  service:
    name: "rexray"
    enabled: yes
    state: started
  ignore_errors: true    
