---

- stat: path=/etc/mesos-slave
  register: mesos_slave_dir

- name: Create mesos-slave directory
  file: dest=/etc/mesos-slave state=directory mode=0755
  when: mesos_slave_dir.stat.exists == False

- name: download rexray
  shell: "curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable"

- name: copy rexray config
  template: src=rexray-config.yml.j2 dest=/etc/rexray/config.yml mode=0644
  
- name: start and enable rexray
  service: name=rexray state=started enabled=yes
