---

- name: install packages centos
  yum:
    name:
      - curl
      - s3fs-fuse
      - ceph-common
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"  

- name: download rexray
  shell: "curl -sSL https://rexray.io/install | sh -s -- stable 0.11.4"

- name: copy rexray config
  template: src=rexray-config.yml.j2 dest=/etc/rexray/config.yml mode=0644
  
- name: start and enable rexray
  service: name=rexray state=restarted enabled=yes
