---

- name: download Weave
  get_url: url=https://github.com/weaveworks/weave/releases/download/{{ weave_version }}/weave dest=/usr/local/bin/ mode=0755

- name: copy Weave systemd scripts into place
  copy: src={{ item }} dest=/etc/systemd/system mode=0755
  with_items:
    - weave.service

- name: copy Weave systemd docker config for Mesos slave
  copy: src=docker_socket dest=/etc/mesos-slave/ mode=0644

- name: copy Weave env
  template: src=weave.env.j2 dest=/etc/weave.env mode=0644

- name: reload systemd
  command: systemctl daemon-reload
  
- name: restart mesos-slave
  service: name=mesos-slave enabled=yes state=restarted

- name: pull weave image
  command: /usr/local/bin/weave setup

- name: start weave
  service:
    name: "weave"
    enabled: yes
    state: restarted
  ignore_errors: true    
  
- name: add motd
  template: src=motd.j2 dest=/etc/motd mode=0644

- name: wait for weave port to be ready
  wait_for:
    port: 6783
    delay: 10
