---

- name: download Weave
  get_url: url=https://github.com/weaveworks/weave/releases/download/{{ weave_version }}/weave dest=/usr/local/bin/ mode=0755

- name: copy Weave systemd scripts into place
  copy: src={{ item }} dest=/etc/systemd/system mode=0755
  with_items:
    - weave.service

- name: copy weave cleanup script
  copy: src={{ item }} dest=/root/ mode=0755
  with_items:
    - weave_cleanup.sh

- name: Add cron job to prune old weave network interfaces
  cron:
    name: "delete all unused weave network interfaces "
    hour: "0"    
    job: "/root/weave_cleanup.sh"
    state: present    

- name: copy Weave systemd docker config for Mesos slave
  copy: src=docker_socket dest={{ mesos_etc_dir }}/ mode=0644

- name: copy Weave env
  template: src=weave.env.j2 dest=/etc/weave.env mode=0644

- name: reload systemd
  command: systemctl daemon-reload
  
- name: pull weave image
  command: /usr/local/bin/weave setup

- name: start weave
  service:
    name: "weave"
    enabled: yes
    state: started
  ignore_errors: true    
  

