---

- name: download Weave scope
  get_url: url=http://git.io/scope dest=/usr/local/bin/ mode=0755

- name: copy WeaveScope systemd scripts into place
  copy: src={{ item }} dest=/etc/systemd/system mode=0755
  with_items:
    - weavescope.service

- name: copy weavescope environment
  template: src=weave_scope.env.j2 dest=/etc/weave_scope.env mode=0644
  notify: restart mesos-slave

- service:
    name: weavescope
    state: restarted

- service:
    name: weavescope
    enabled: yes
    state: started
    


