---

- name: download Weave scope
  get_url: url=https://github.com/weaveworks/weave/releases/download/{{ weave_version }}/weave dest=/usr/local/bin/ mode=0755

- name: copy WeaveScope systemd scripts into place
  copy: src={{ item }} dest=/etc/systemd/system mode=0755
  with_items:
    - weavescope.service

- name: copy weavescope environment
  template: src=weave_scope.env.j2 dest=/etc/weave_scope.env mode=0644
  
- name: pull weave image
  command: /usr/local/bin/weave setup 

- name: reload systemd
  command: systemctl daemon-reload
  
- name: restart mesos-slave
  service: name=mesos-slave enabled=yes state=restarted

- name: start weave scope
  service:
    name: weavescope
    enabled: yes
    state: started
    


