---

mesos_password: "marathon"
mesos_user: "marathon"
mesos_clustername: "DEFAULT"
quorum: "1"

libprocess_enable_ssl: "false"
libprocess_enable_ssl_verify: "false"
libprocess_ssl_require_cert: "false"
libprocess_ssl_enable_downgrade: "true"

mesos_rpm: "mesos-1.10.0"

mesos_ssl_key: "../files/mesos.key"
mesos_ssl_crt: "../files/mesos.crt"

mesos_ip_address: "{{ ansible_default_ipv4.address }}"


