---

- name: download and run rexray aws efs plugin
  shell: "docker plugin install --grant-all-permissions {{ rexray_image_efs }} EFS_ACCESSKEY={{ efs_access_key }} EFS_SECRETKEY={{ efs_secret_key}} EFS_REGION={{ efs_region }}"
  ignore_errors: true
