---
prometheus_release: "1.7.1"
alertmanager_release: "0.7.1"

prometheus_package: "prometheus-{{ prometheus_release }}.linux-amd64.tar.gz"
prometheus_archive_contents: "prometheus-{{ prometheus_release }}.linux-amd64"
prometheus_url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_release }}/{{ prometheus_package }}"

prometheus_user: "prometheus"
prometheus_group: "prometheus"

alertmanager_prometheus_url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_release }}/alertmanager-{{ alertmanager_release }}.linux-amd64.tar.gz"
alertmanager_prometheus_package: "alertmanager-{{ alertmanager_release }}.linux-amd64.tar.gz"
