---

- name: Check cgroups version
  stat:
    path: /sys/fs/cgroup/cpu 
  register: cg_result

- name: Raise failure if cgroups v2 is enable  
  fail:
    msg: "Please enable CGoups Version 1 (systemd.unified_cgroup_hierarchy=0)"
  when: not cg_result.stat.exists

- name: "get facts of installed packages"
  package_facts:
    manager: "auto"

- name: update repository cache ubuntu
  apt:
    update_cache: true
  when:
    ansible_os_family == "Debian"

- name: install os packages
  package:
    name:
      - gnupg
    state: present

- name: deactivate selinux permanent
  lineinfile:
    dest: /etc/sysconfig/selinux
    regexp: ^SELINUX=
    line: SELINUX=disabled
    state: present
    create: yes
  when: "'policycoreutils' is in ansible_facts.packages"      

- name: check if setenforce command exists
  stat:
    path: /usr/sbin/setenforce
  register: setenforce

- name: deactivate selinux temp
  command: setenforce 0
  when: setenforce.stat.exists
    

