---

- name: Get facts of installed packages
  ansible.builtin.package_facts:
    manager: "auto"

- name: Update repository cache ubuntu
  ansible.builtin.apt:
    update_cache: true
  when:
    ansible_os_family == "Debian"
  ignore_errors: true

- name: Install os packages
  ansible.builtin.package:
    name:
      - gnupg
      - net-tools
    state: present

- name: Deactivate selinux permanent
  ansible.builtin.lineinfile:
    dest: /etc/sysconfig/selinux
    regexp: ^SELINUX=
    line: SELINUX=disabled
    state: present
    create: true
  when: "'policycoreutils' is in ansible_facts.packages"

- name: Check if setenforce command exists
  ansible.builtin.stat:
    path: /usr/sbin/setenforce
  register: setenforce

- name: Deactivate selinux temp
  ansible.builtin.command: setenforce 0
  when: setenforce.stat.exists
  ignore_errors: true

- name: Deactivate Firewalld
  service:
    name: firewalld
    enabled: no
    state: stopped
  ignore_errors: true
  when: "'firewalld' is in ansible_facts.packages"

- name: Deactivate UFW
  service:
    name: ufw
    enabled: no
    state: stopped
  ignore_errors: true
  when: "'ufw' is in ansible_facts.packages"


