---

- name: install dnsmasq packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnsmasq
    - bind-utils
    - NetworkManager

- name: collect nameservers
  sudo: yes
  shell: "cat /etc/resolv.conf | grep -i '^nameserver' | cut -d ' ' -f2"
  register: nameservers_output

- name: collect dns search list
  sudo: yes
  shell: "cat /etc/resolv.conf | grep -i '^search' | cut -d ' ' -f2- | tr ' ' '\n'"
  register: dns_search_list_output

- name: set nameservers
  set_fact:
    nameservers: "{{ nameservers_output.stdout_lines }}"

- name: set dns search list
  set_fact:
    domain_search_list: "{{ dns_search_list_output.stdout_lines }}"

- name: ensure dnsmasq.d directory exists
  sudo: yes
  file:
    path: /etc/dnsmasq.d/
    state: directory

- name: configure dnsmasq for consul
  sudo: yes
  template:
    src: 10-consul
    dest: /etc/dnsmasq.d/10-consul
    mode: 0755

- name: enable dnsmasq
  sudo: yes
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: add dnsmasq to /etc/resolv.conf
  sudo: yes
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
