---

- name: "get facts of installed packages"
  package_facts:
    manager: "auto"

- name: install dnsmasq packages centos
  package:
    name: 
      - dnsmasq
      - bind-utils
    state: present
  when:
    ansible_os_family == "RedHat"

- name: install dnsmasq packages ubuntu
  package:
    name: 
      - dnsmasq
      - dnsutils
    state: present
  when:
    ansible_os_family == "Debian"

- name: disable update resolv conf of network manager
  copy: src=NetworkManager.conf dest=/etc/NetworkManager/NetworkManager.conf mode=0644
  when: "'NetworkManager' is in ansible_facts.packages"      

- name: disable update resolv conf of dhclient
  copy: src=dhclient-enter-hooks dest=/etc/dhclient-enter-hooks mode=0755

- name: restart NetworkManager if its installed
  service:
    name: NetworkManager
    state: restarted
    enabled: yes   
  when: "'NetworkManager' is in ansible_facts.packages"      

- name: collect nameservers
  shell: "cat /etc/resolv.conf | grep -i '^nameserver' | cut -d ' ' -f2"
  register: nameservers_output

- name: collect dns search list
  shell: "cat /etc/resolv.conf | grep -i '^search' | cut -d ' ' -f2- | tr ' ' '\n'"
  register: dns_search_list_output

- name: set nameservers
  set_fact:
    nameservers: "{{ nameservers_output.stdout_lines }}"

- name: set dns search list
  set_fact:
    domain_search_list: "{{ dns_search_list_output.stdout_lines }}"

- name: except docker interface
  lineinfile: 
    dest: "/etc/dnsmasq.conf"
    create: yes 
    state: present 
    regexp: "^except-interface=*" 
    line: "except-interface=docker0" 

- name: set bind interface
  lineinfile: 
    dest: "/etc/dnsmasq.conf"
    create: yes 
    state: present 
    regexp: "^bind-interfaces*" 
    line: "bind-interfaces" 

- name: ensure dnsmasq.d directory exists
  file:
    path: /etc/dnsmasq.d/
    state: directory

- name: configure dnsmasq for mesos-dns
  template:
    src: 20-mesos
    dest: /etc/dnsmasq.d/20-mesos
    mode: 0644    

- name: configure dnsmasq for weave
  template:
    src: 30-weave
    dest: /etc/dnsmasq.d/30-weave
    mode: 0644    

- name: enable dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: add dnsmasq to /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
  ignore_errors: true    


- name: forbid changes at resolv.conf
  command: chattr +i /etc/resolv.conf
