---

- shell: cat /tmp/hvm.type
  register: hvm_type

- name: install packages
  sudo: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - dnsmasq
    - bind-utils
    - NetworkManager

- name: collect nameservers
  sudo: yes
  shell: "cat /etc/resolv.conf | grep -i '^nameserver' | cut -d ' ' -f2"
  register: nameservers_output

- name: collect dns search list
  sudo: yes
  shell: "cat /etc/resolv.conf | grep -i '^search' | cut -d ' ' -f2- | tr ' ' '\n'"
  register: dns_search_list_output

- name: set nameservers
  set_fact:
    nameservers: "{{ nameservers_output.stdout_lines }}"

- name: set dns search list
  set_fact:
    domain_search_list: "{{ dns_search_list_output.stdout_lines }}"

- name: ensure dnsmasq.d directory exists
  sudo: yes
  file:
    path: /etc/NetworkManager/dnsmasq.d
    state: directory

- name: configure dnsmasq for consul
  sudo: yes
  template:
    src: 10-consul
    dest: /etc/dnsmasq.d/10-consul
    mode: 0755
  when: "'vagrant' not in hvm_type.stdout"

- name: configure dnsmasq for consul
  sudo: yes
  template:
    src: 10-consul.vagrant
    dest: /etc/dnsmasq.d/10-consul
    mode: 0755
  when: "'vagrant' in hvm_type.stdout"

- name: enable dnsmasq
  sudo: yes
  service:
    name: dnsmasq
    state: started
    enabled: yes

- name: configure networkmanager for dnsmasq
  sudo: yes
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    line: "dns=none"
    insertafter: "^\\[main\\]$"
  notify:
    - restart networkmanager

- name: List network-scripts which need fixup
  sudo: yes
  shell: "find /etc/sysconfig/network-scripts -name 'ifcfg-*'"
  register: list_of_network_scripts

- name: fixing PEERDNS in network-scripts
  sudo: yes
  lineinfile:
    dest: "{{ item }}"
    line: "PEERDNS=no"
    regexp: ^PEERDNS=.*'
  with_items: "{{ list_of_network_scripts.stdout_lines }}"  
  notify:
    - restart networkmanager

- name: add dnsmasq to /etc/resolv.conf
  sudo: yes
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
  when: "'vagrant' not in hvm_type.stdout"

- name: add dnsmasq to /etc/resolv.conf
  sudo: yes
  template:
    src: resolv.conf.vagrant.j2
    dest: /etc/resolv.conf
    mode: 0644
  when: "'vagrant' in hvm_type.stdout"
