---

- name: copy Weave expose systemd scripts into place
  copy: src={{ item }} dest=/etc/systemd/system mode=0755
  with_items:
    - weaveexpose.service

- name: reload systemd
  command: systemctl daemon-reload
  
- name: start weave scope
  service:
    name: weaveexpose
    enabled: yes
    state: restarted
  ignore_errors: true    
    


