---
  - name: add cni plugin dir
    lineinfile: 
      dest: /etc/mesos-slave/network_cni_plugins_dir 
      state: present 
      line: "/opt/cni/bin" 
      create: yes 

  - name: create cni directory
    file: 
      state: directory
      path: "/etc/cni/net.d"

  - name: add cni config dir
    lineinfile: 
      dest: "/etc/mesos-slave/network_cni_config_dir "
      state: present 
      line: "/etc/cni/net.d" 
      create: yes  

