---

  - name: Creates cni directory if its not exist
    file:
      path: "{{ mesos_etc_dir }}/net.d"
      state: directory
      recurse: yes

  - name: add cni config dir
    lineinfile: 
      dest: "{{ mesos_etc_dir }}/network_cni_config_dir"
      state: present 
      line: "{{ mesos_etc_dir}}/cni/net.d" 
      create: yes  
  
  - name: copy cni config
    copy: 
      src: 20-weave.conf
      dest: "{{ mesos_etc_dir }}/cni/net.d/20-weave.conf"
      mode: 0644

  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      remote_src: true
      src: "/opt/cni/bin/{{ item }}"
      dest: /usr/lib/cni/
      mode: '0755'
    with_items:
      - weave-plugin-2.8.1
      - weave-ipam
      - weave-net


      

