---

  - name: Creates cni directory if its not exist
    file:
      path: /etc/mesos/cni/net.d
      state: directory
      recurse: yes

  - name: add cni config dir
    lineinfile: 
      dest: "{{ mesos_etc_dir }}/network_cni_config_dir"
      state: present 
      line: "/etc/mesos/cni/net.d" 
      create: yes  
  
  - name: copy cni config
    copy: 
      src: weave.conflist
      dest: /etc/mesos/cni/net.d/10-weave.conflist
      mode: 0644

