---

  - name: create cni directory
    file: 
      state: directory
      path: "/etc/cni/net.d"

  - name: create cni directory
    file: 
      state: directory
      path: "/etc/cni/bin"

  - name: add cni config dir
    lineinfile: 
      dest: /etc/mesos-slave/network_cni_config_dir
      state: present 
      line: "/etc/cni/net.d" 
      create: yes  
  
  - name: add cni plugin dir
    lineinfile: 
      dest: /etc/mesos-slave/network_cni_plugins_dir 
      state: present 
      line: "/opt/cni/bin" 
      create: yes       

  - name: copy cni config
    copy: 
      src: weave.conflist
      dest: /etc/cni/net.d/10-weave.conflist
      mode: 0644

  - name: restart mesos-slave
    command: systemctl restart mesos-slave

