---

- name: enable mesos update
  lineinfile:
    dest: "/etc/yum.conf"
    regexp: "^exclude=mesos-*"
    line: '#exclude=mesos-*'
    state: present

- name: install mesos slave packages
  yum:
    name:
      - "{{ mesos_rpm }}"
    state: present

- name: disable mesos update
  lineinfile:
    dest: "/etc/yum.conf"
    regexp: "^#exclude=mesos-*"
    line: 'exclude=mesos-*'
    state: present
    
- name: Remove deprecated config files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/mesos-agent/modules"

- name: create zk file
  file: 
    path: /etc/mesos/zk 
    state: touch
    mode: 0640

- name: create ssl directory
  file: 
    path: /etc/mesos/ssl
    state: directory
    mode: 0755

- name: copy ssl cert
  copy:
    src: "{{ mesos_ssl_crt }}"
    dest: /etc/mesos/ssl/mesos.crt
    mode: 0644
  tags:
    - cert

- name: copy ssl key
  copy:
    src: "{{ mesos_ssl_key }}"
    dest: /etc/mesos/ssl/mesos.key
    mode: 0644
  tags:
    - cert

- name: Remove deprecated config files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/mesos-agent/seccomp_config_dir"  
    - "/etc/mesos-agent/seccomp_profile_name"
    - "/etc/default/mesos"
    - "/etc/default/mesos-agent"
    - "/etc/mesos/modules/logrotate.config"

- name: Check if old mesos-slave folder exist
  stat: path=/etc/mesos-slave
  register: mesos_slave

- name: Rename old mesos-slave folder to mesos-agent
  command: mv /etc/mesos-slave /etc/mesos-agent
  when: mesos_slave.stat.exists

- name: Check if old mesos-slave config file
  stat: path=/etc/default/mesos-slave
  register: default_mesos_slave

- name: Rename old mesos-slave config to mesos-agent
  command: mv /etc/default/mesos-slave /etc/default/mesos-agent
  when: default_mesos_slave.stat.exists

- name: configure zk access
  lineinfile: dest=/etc/mesos/zk create=yes state=present regexp="^zk=*" line="zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos" mode=0640

- name: configure master access
  lineinfile: dest=/etc/mesos-agent/master create=yes state=present regexp="^zk=*" line="zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos" mode=0640

- name: configure user env string
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^USER=*" line="USER=root"   mode=0640

- name: enable ssl for mesos libprocess
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_ENABLED=*" line="LIBPROCESS_SSL_ENABLED={{ libprocess_enable_ssl }}" mode=0640

- name: enable ssl verify for mesos
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_VERIFY_CERT=*" line="LIBPROCESS_SSL_VERIFY_CERT={{ libprocess_enable_ssl_verify }}"  mode=0640

- name: add mesos libprocess ssl key file
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_KEY_FILE=*" line="LIBPROCESS_SSL_KEY_FILE=/etc/mesos/ssl/mesos.key"  mode=0640

- name: add mesos libprocess ssl cert file
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_CERT_FILE=*" line="LIBPROCESS_SSL_CERT_FILE=/etc/mesos/ssl/mesos.crt"  mode=0640

- name: enable required ssl cert
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_REQUIRE_CERT=*" line="LIBPROCESS_SSL_REQUIRE_CERT={{ libprocess_ssl_require_cert }}"  mode=0640

- name: set ulimit
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^ULIMIT=*" line="ULIMIT=\"-n {{ mesos_ulimit }}\""  mode=0640

- name: set logs dir
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LOGS=*" line="LOGS={{ mesos_logs_dir }}"  mode=0640

- name: configure mesos-zk string
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^MESOS_ZK=*" line="MESOS_ZK=file:///etc/mesos/zk"

- name: set mesos libprocess ssl downgrade
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^LIBPROCESS_SSL_ENABLE_DOWNGRADE=*" line="LIBPROCESS_SSL_ENABLE_DOWNGRADE={{ libprocess_ssl_enable_downgrade }}" mode=0640

- name: set hostname in mesos
  lineinfile: dest=/etc/mesos-agent/hostname state=present regexp="^" line="{{ inventory_hostname }}" create=yes mode=0640

- name: increase the mesos-slave executor timeout
  lineinfile: dest=/etc/mesos-agent/executor_registration_timeout state=present line="5mins" regexp="^" create=yes mode=0640

- name: add containerizer to the mesos-slave
  lineinfile: dest=/etc/mesos-agent/containerizers state=present line="docker,mesos" regexp="^" create=yes mode=0640

- name: add mesos-slave credentials
  lineinfile: dest=/etc/mesos-agent/credential state=present line="/etc/mesos/credential" regexp="^" create=yes mode=0640

- name: add mesos-slave http credentials
  lineinfile: dest=/etc/mesos-agent/http_credentials state=present line="/etc/mesos/http_credentials" regexp="^" create=yes mode=0640

- name: enable cluster http readonly authentication
  lineinfile: dest=/etc/mesos-agent/authenticate_http_readonly state=present create=yes regexp="^" line="true" mode=0640

- name: enable cluster http readwrite authentication
  lineinfile: dest=/etc/mesos-agent/authenticate_http_readwrite state=present create=yes regexp="^" line="true" mode=0640

- name: enable cluster http authenticators
  lineinfile: dest=/etc/mesos-agent/http_authenticators state=present create=yes regexp="^" line="basic" mode=0640

- name: add weave.socks to the mesos-slave
  lineinfile: dest=/etc/mesos-agent/docker_socket state=present line="/var/run/weave/weave.sock" regexp="^" create=yes mode=0640

- name: set slave ip in mesos
  lineinfile: dest=/etc/mesos-agent/ip state=present create=yes regexp="^" line="{{ mesos_ip_address }}" mode=0640

- name: disable hostname lookup
  lineinfile: dest=/etc/mesos-agent/hostname_lookup state=present create=yes regexp="^" line="false" mode=0640

- name: set memory profiling
  lineinfile: dest=/etc/mesos-agent/memory_profiling state=present create=yes regexp="^" line="true" mode=0640

- name: set mesos isolation
  lineinfile: dest=/etc/mesos-agent/isolation state=present create=yes regexp="^" line="cgroups/all,disk/du,network/cni,filesystem/linux,docker/runtime,volume/sandbox_path,volume/secret,posix/rlimits,namespaces/pid,linux/capabilities" mode=0640

- name: set image provider
  lineinfile: dest=/etc/mesos-agent/image_providers state=present create=yes regexp="^" line="appc,docker" mode=0640

- name: set mesos module directory
  lineinfile: dest=/etc/mesos-agent/modules_dir state=present create=yes regexp="^" line="/etc/mesos/modules" mode=0640

- name: set mesos work-dir
  lineinfile: dest=/etc/mesos-agent/work_dir state=present create=yes regexp="^" line="/var/lib/mesos" mode=0755

- name: set mesos executor env with ssl
  template: 
    src: executor.json.js
    dest: /etc/mesos-agent/executor_environment_variables
    mode: 0640
  when:
    - libprocess_enable_ssl == "true"

- name: set mesos executor env without ssl
  file:
    path: /etc/mesos-agent/executor_environment_variables
    state: absent
  when:
    - libprocess_enable_ssl == "false"

- name: set mesos container dns
  template: 
    src: container_dns.j2
    dest: /etc/mesos-agent/default_container_dns
    mode: 0640

- name: create mesos module directory
  file:
    path: /etc/mesos/modules
    state: directory
    mode: 0750    

- name: create mesos seccomp directory
  file:
    path: /etc/mesos/seccomp
    state: directory
    mode: 0750    

- name: copy mesos seccomp default profile
  copy:
    src: default.json
    dest: /etc/mesos/seccomp/default.json
    mode: 0640

- name: copy mesos credential
  template: src=credential.j2 dest=/etc/mesos/credential mode=0640  

- name: copy mesos http credential
  template: src=http_credentials.j2 dest=/etc/mesos/http_credentials mode=0640  

- name: ensure mesos-slave service is started and enabled
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - mesos-slave
  tags:
    - cert

- name: ensure mesos-master service is disabled
  service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - mesos-master
