---

- name: add docker repo
  copy: src=docker-main.repo dest=/etc/yum.repos.d/docker-main.repo mode=0644

- name: install docker packages
  yum: name={{ item }} state=latest
  with_items:
    - docker

- name: configure docker dns
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: ^OPTIONS=
    line: OPTIONS=' --dns {{ client_address }} --dns-search {{ consul_domain }} --selinux-enabled --log-driver=journald --signature-verification=false '
    state: present
    create: yes

- name: copy new docker systemd config
  copy: src=docker.systemd dest=/etc/systemd/system/docker.service mode=0755

- name: reload systemd
  shell: systemctl daemon-reload

- name: add docker to systemd init
  service: name=docker enabled=yes state=started
