---

- name: add docker repo
  copy: src=docker-main.repo dest=/etc/yum.repos.d/docker-main.repo mode=0644 

- name: install docker packages
  yum: name={{ item }} state=latest
  with_items:
    - docker-engine

- name: configure docker dns
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: ^OPTIONS=
    line: OPTIONS=' --dns {{ client_address }} --dns-search {{ consul_domain }} --log-driver=journald  '
    state: present
    create: yes

- name: create Docker directory
  file: path=/etc/docker state=directory

- name: copy new docker systemd config
  copy: src=docker.systemd dest=/etc/systemd/system/docker.service mode=0755

- name: copy new docker daemone config
  copy: src=daemon.json dest=/etc/docker/daemon.json mode=0640

- name: reload systemd
  shell: systemctl daemon-reload

- name: add docker to systemd init
  service: name=docker enabled=yes state=started
