---

- name: add docker repo
  copy: src=docker-ce.repo dest=/etc/yum.repos.d/docker-main.repo mode=0644 

- name: install docker packages
  yum:
    name:
      - e2fsprogs
      - xfsprogs
      - docker-ce-18.06.1.ce
    state: installed

- name: configure docker dns
  lineinfile:
    dest: /etc/sysconfig/docker
    regexp: ^OPTIONS=
    line: OPTIONS=' --dns {{ ansible_default_ipv4.address }} --dns-search {{ consul_domain }} --log-driver=journald  '
    state: present
    create: yes

- name: create Docker directory
  file: path=/etc/docker state=directory

- name: copy new docker systemd config
  copy: src=docker.systemd dest=/etc/systemd/system/docker.service mode=0755

- name: copy new docker daemone config
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json mode=0640

- name: Add cron job to prune docker images
  cron:
    name: "delete all unused docker images "
    minute: "0"
    job: "docker image prune -a -f > /dev/null"
    state: present

- name: Add cron job to prune docker containers
  cron:
    name: "prune docker containers"
    minute: "0"
    job: "docker container prune -f > /dev/null"
    state: present  

- name: Add cron job to prune local docker volumes
  cron:
    name: "prune local docker volumes"
    minute: "0"
    job: "docker volume prune -f > /dev/null"
    state: present

- name: reload systemd
  shell: systemctl daemon-reload

- name: add docker to systemd init
  service: name=docker enabled=yes state=started
