---
- name: Install grafana packages
  yum:
    name:
      - "{{ grafana_url }}"
    state: installed

- name: copy config to host
  template:
    src: "{{ item }}.j2"
    dest: "{{ grafana_conf_dir }}/{{ item }}"
    owner: "{{ grafana_uid }}"
    group: "{{ grafana_gid }}"
  with_items:
  - datasources.yaml
  - dashboards.yaml

- name: copy nodes-dashboard to host
  template:
    src: "{{ item }}.j2"
    dest: "{{ grafana_dashboard_dir }}/{{ item }}"
    owner: "{{ grafana_uid }}"
    group: "{{ grafana_gid }}"
  with_items:
  - node-exporter-metrics.json
  - docker.json
  - platform.json
  - docker-metric.json

- name: enable graylog server as startup
  service: 
    name: "grafana-server" 
    state: started
    enabled: yes

