---

  - name: Create User 
    user: 
      name: "{{ item }}"
      group: users
    with_items:
      - "{{ ssh_user_1 }}"

  - name: Set authorized key
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', 'pubkeys/{{ item }}.pub') }}"
    with_items:
      - "{{ ssh_user_1 }}"
      
