---

- name: Build hosts file for all server
  ansible.builtin.blockinfile:
    dest: /etc/hosts
    block: "{{ lookup('template', 'hosts.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK "

- name: Set server hostnamectl
  ansible.builtin.shell: "hostnamectl set-hostname {{ ansible_host }}"

- name: Restart dnsmasq if its installed
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
    enabled: true

