---

- name: install mesos repo
  yum:
    name: http://repos.mesosphere.io/el/7/noarch/RPMS/{{ mesosphere_repo }}
    state: present

- name: install mesos master packages
  yum: name={{ item }} state=latest
  with_items:
    - mesos
    - mesosphere-zookeeper

- name: disable mesos update
  lineinfile:
    dest=/etc/yum.conf
    line="{{ item.line }}"
    state=present
  with_items:
    - { line: 'exclude=mesos-*' }

- name: set master ID
  lineinfile: dest=/var/lib/zookeeper/myid state=present regexp="^" line="{{ myid }}" create=yes

- name: remove server line in zookeeper config
  lineinfile:
    dest=/etc/zookeeper/conf/zoo.cfg    
    state=absent
    regexp='^server.' 

- name: add zookeepers to config
  lineinfile:
    dest=/etc/zookeeper/conf/zoo.cfg
    line="{{ item }}"
    state=present
  with_items:
    - "{% for host in groups['master'] %}server.{{ hostvars[host].myid }}={{ hostvars[host].client_address }}:2888:3888\n{% endfor %}"

- name : Start zookeeper server and enable at reboot
  service : name=zookeeper state=restarted enabled=yes

- name: Delete old zk entry
  file: path=/etc/mesos/zk state=absent

- name: configure zk access
  lineinfile: dest=/etc/mesos/zk create=yes state=present regexp="^zk" line="zk://{% for host in groups['master'] %}{{ hostvars[host].client_address }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

#- name: clean blank spaces in zk config
#  shell: sed -i '/^\s*$/d' /etc/mesos/zk

- name: set quorom count
  lineinfile: dest=/etc/mesos-master/quorum state=present regexp="^" line="{{ quorum }}" create=yes
#  replace: dest=/etc/mesos-master/quorum regexp='^' replace='{{ quorum }}'

- name: set hostname in mesos
  lineinfile: dest=/etc/mesos-master/hostname state=present regexp="^" line="{{ inventory_hostname }}" create=yes

- name: set master ip in mesos
  lineinfile: dest=/etc/mesos-master/ip state=present create=yes regexp="^" line="{{ client_address }}"

- name: set cluster hostname
  lineinfile: dest=/etc/mesos-master/cluster state=present create=yes regexp="^" line="{{ mesos_clustername }}"

- name: enable cluster authentication
  lineinfile: dest=/etc/mesos-master/authenticate state=present create=yes regexp="^" line="true"

- name: enable cluster agent authentication
  lineinfile: dest=/etc/mesos-master/authenticate_agents state=present create=yes regexp="^" line="true"

- name: enable cluster credentials
  lineinfile: dest=/etc/mesos-master/credentials state=present create=yes regexp="^" line="/etc/mesos/credentials"

- name: create marathon secret
  lineinfile: dest=/etc/mesos/marathon.secret state=present create=yes regexp="^" line="{{ mesos_password }}"

- name: copy mesos credentials
  template: src=credentials.j2 dest=/etc/mesos/credentials mode=0640

- name: start necessary services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - mesos-master
