---

- shell: cat /tmp/master.count
  register: master_result

- name: install mesos master packages
  yum: name={{ item }} state=latest
  with_items:
    - "{{ stable_mesos_package_version }}"
    - mesosphere-zookeeper

- name: disable mesos update
  lineinfile:
    dest=/etc/yum.conf
    line="{{ item.line }}"
    insertafter='EOF'
  with_items:
    - { line: 'exclude=mesos-*' }

- name: set master ID
  lineinfile: dest=/var/lib/zookeeper/myid state=present regexp="^" line="{{ myid }}" create=yes

- name: add zookeepers to config
  lineinfile:
    dest=/etc/zookeeper/conf/zoo.cfg
    line="{{ item.line }}"
    insertafter='EOF'
  with_items:
    - "{% for host in groups['master'] %} { line: 'server.{{ host.myid }}={{ host.client_address }}:2888:3888' } {% endfor %}"

- name : Start zookeeper server and enable at reboot
  service : name=zookeeper state=restarted enabled=yes

- name: Delete old zk entry
  file: path=/etc/mesos/zk state=absent

- name: configure zk access
  lineinfile: dest=/etc/mesos/zk create=yes state=present regexp="^zk" line="zk://{% for host in groups['master'] %}{{ host.client_address }}:2181 }{% if not loop.last %},{% endif %} {% endfor %}:2181/mesos"

- name: clean blank spaces in zk config
  shell: sed -i '/^\s*$/d' /etc/mesos/zk

- name: set quorom count
  replace: dest=/etc/mesos-master/quorum regexp='^$' replace='{{ quorum }}'

- name: set hostname in mesos
  lineinfile: dest=/etc/mesos-master/hostname state=present line="{{ host }}" create=yes

- name: set master ip in mesos
  lineinfile: dest=/etc/mesos-master/ip state=present create=yes line="{{ client_address }}"

- name: set cluster hostname
  lineinfile: dest=/etc/mesos-master/cluster state=present create=yes line="{{ mesos_cluster_name }}"

- name: start necessary services
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - mesos-master
