---
- name: install mesos master packages
  yum:
    name:
      - mesos-1.8.0
      - mesosphere-zookeeper-3.4.6
    state: installed

- name: disable mesos update
  lineinfile:
    dest=/etc/yum.conf
    line="{{ item.line }}"
    state=present
  with_items:
    - { line: 'exclude=mesos-*' }

- name: enable zookeeper authentication
  lineinfile: dest=/etc/zookeeper/conf/java.env state=present regexp="^" line="SERVER_JVMFLAGS=\"-Djava.security.auth.login.config=/etc/zookeeper/conf/jaas.conf\"" create=yes

- name: set master ID
  lineinfile: dest=/var/lib/zookeeper/myid state=present regexp="^" line="{{ myid }}" create=yes

- name: remove server line in zookeeper config
  lineinfile:
    dest=/etc/zookeeper/conf/zoo.cfg    
    state=absent
    regexp='^server.' 

- name: add zookeepers to config
  lineinfile:
    dest=/etc/zookeeper/conf/zoo.cfg
    line="{{ item }}"
    state=present
  with_items:
    - "{% for host in groups['manager'] %}server.{{ hostvars[host].myid }}={{ host }}:2888:3888\n{% endfor %}"

- name: add sasl to config
  lineinfile:
    dest=/etc/zookeeper/conf/zoo.cfg
    line="{{ item }}"
    state=present
  with_items:
    - "authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider"
    - "requireClientAuthScheme=sasl"

- name: Remove deprecated config files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/mesos-master/authenticate"

- name : Start zookeeper server and enable at reboot
  service : name=zookeeper state=restarted enabled=yes

- name: Delete old zk entry
  file: path=/etc/mesos/zk state=absent

- name: configure zk access
  lineinfile: dest=/etc/mesos/zk create=yes state=present regexp="^zk" line="zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: configure mesos-master string
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^MESOS_MASTER=*" line="MESOS_MASTER=zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: set quorom count
  lineinfile: dest=/etc/mesos-master/quorum state=present regexp="^" line="{{ quorum }}" create=yes
#  replace: dest=/etc/mesos-master/quorum regexp='^' replace='{{ quorum }}'

- name: set hostname in mesos
  lineinfile: dest=/etc/mesos-master/hostname state=present regexp="^" line="{{ inventory_hostname }}" create=yes

- name: set master ip in mesos
  lineinfile: dest=/etc/mesos-master/ip state=present create=yes regexp="^" line="{{ ansible_default_ipv4.address }}"

- name: set cluster hostname
  lineinfile: dest=/etc/mesos-master/cluster state=present create=yes regexp="^" line="{{ mesos_clustername }}"

- name: enable cluster authentication
  lineinfile: dest=/etc/mesos-master/authenticate_frameworks state=present create=yes regexp="^" line="true"

- name: enable cluster http readwrite authentication
  lineinfile: dest=/etc/mesos-master/authenticate_http_readwrite state=present create=yes regexp="^" line="true"    

- name: enable cluster http readonly authentication
  lineinfile: dest=/etc/mesos-master/authenticate_http_readonly state=present create=yes regexp="^" line="true"      

- name: enable cluster agent authentication
  lineinfile: dest=/etc/mesos-master/authenticate_agents state=present create=yes regexp="^" line="true"

- name: enable cluster credentials
  lineinfile: dest=/etc/mesos-master/credentials state=present create=yes regexp="^" line="/etc/mesos/credentials"

- name: enable cluster acls
  lineinfile: dest=/etc/mesos-master/acls state=present create=yes regexp="^" line="file:///etc/mesos/acls"

- name: disable hostname lookup
  lineinfile: dest=/etc/mesos-master/hostname_lookup state=present create=yes regexp="^" line="false"

- name: set slave ping timeouts
  lineinfile: dest=/etc/mesos-master/max_agent_ping_timeouts state=present create=yes regexp="^" line="20"

- name: set memory profiling
  lineinfile: dest=/etc/mesos-master/memory_profiling state=present create=yes regexp="^" line="true"

- name: set offer timeout
  lineinfile: dest=/etc/mesos-master/offer_timeout state=present create=yes regexp="^" line="2mins"

- name: set role sorter
  lineinfile: dest=/etc/mesos-master/role_sorter state=present create=yes regexp="^" line="random"

- name: set framework sorter
  lineinfile: dest=/etc/mesos-master/framework_sorter state=present create=yes regexp="^" line="random"

- name: set slave removal rate limit
  lineinfile: dest=/etc/mesos-master/agent_removal_rate_limit state=present create=yes regexp="^" line="100/1mins"

- name: set mesos module directory
  lineinfile: dest=/etc/mesos-master/modules_dir state=present create=yes regexp="^" line="/etc/mesos/modules"

- name: create mesos module directory
  file:
    path: /etc/mesos/modules
    state: directory
    mode: 0750

- name: copy mesos credentials
  template: src=credentials.j2 dest=/etc/mesos/credentials mode=0640

- name: copy mesos acls
  template: src=acls.j2 dest=/etc/mesos/acls mode=0640  

- name: copy marathon secret
  template: src=marathon.secret.j2 dest=/etc/mesos/marathon.secret mode=0640  

- name: copy zookeeper jaas file
  template: src=jaas.conf.j2 dest=/etc/zookeeper/conf/jaas.conf mode=0640  

- name: start necessary services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - mesos-master
