---
  
- name: enable mesos update
  lineinfile:
    dest: "/etc/yum.conf"
    regexp: "^exclude=mesos-*"
    line: '#exclude=mesos-*'
    state: present

- name: install mesos master packages
  yum:
    name:
      - "{{ mesos_rpm }}"
    state: latest

- name: disable mesos update
  lineinfile:
    dest: "/etc/yum.conf"
    regexp: "^#exclude=mesos-*"
    line: 'exclude=mesos-*'
    state: present

- name: Remove deprecated config files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
    - "/etc/mesos-master/authenticate"

- name: create zk file
  file: 
    path: /etc/mesos/zk 
    state: touch
    mode: 0640

- name: create ssl directory
  file: 
    path: /etc/mesos/ssl
    state: directory
    mode: 0755
  tags:
    - cert

- name: copy ssl cert
  copy:
    src: "{{ mesos_ssl_crt }}"
    dest: /etc/mesos/ssl/mesos.crt
    mode: 0644
  tags:
    - cert

- name: copy ssl key
  copy:
    src: "{{ mesos_ssl_key }}"
    dest: /etc/mesos/ssl/mesos.key
    mode: 0644    
  tags:
    - cert

- name: configure zk access
  lineinfile: dest=/etc/mesos/zk create=yes state=present regexp="^zk=*" line="zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: configure mesos-zk string
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^MESOS_ZK=*" line="MESOS_ZK=file:///etc/mesos/zk"

- name: configure user env string
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^USER=*" line="USER=root"  

- name: enable ssl for mesos libprocess
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_ENABLED=*" line="LIBPROCESS_SSL_ENABLED={{ libprocess_enable_ssl }}"  

- name: enable ssl verify for mesos libprocess (deprecated)
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_VERIFY_CERT=*" line="LIBPROCESS_SSL_VERIFY_CERT={{ libprocess_enable_ssl_verify }}"  

- name: enable ssl verify for mesos libprocess
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_VERIFY_SERVER_CERT=*" line="LIBPROCESS_SSL_VERIFY_SERVER_CERT={{ libprocess_enable_ssl_verify }}"  

- name: add mesos libprocess ssl key file
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_KEY_FILE=*" line="LIBPROCESS_SSL_KEY_FILE=/etc/mesos/ssl/mesos.key" 

- name: add mesos libprocess ssl cert file
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_CERT_FILE=*" line="LIBPROCESS_SSL_CERT_FILE=/etc/mesos/ssl/mesos.crt" 

- name: enable required sll cert (deprecated)
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_REQUIRE_CERT=*" line="LIBPROCESS_SSL_REQUIRE_CERT={{ libprocess_ssl_require_cert }}" 

- name: enable required ssl cert 
  lineinfile: dest=/etc/default/mesos create=yes state=present regexp="^LIBPROCESS_SSL_REQUIRE_CLIENT_CERT=*" line="LIBPROCESS_SSL_REQUIRE_CLIENT_CERT={{ libprocess_ssl_require_cert }}"  mode=0640


- name: set mesos libprocess ssl downgrade
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^LIBPROCESS_SSL_ENABLE_DOWNGRADE=*" line="LIBPROCESS_SSL_ENABLE_DOWNGRADE={{ libprocess_ssl_enable_downgrade }}" 

- name: set quorom count
  lineinfile: dest=/etc/mesos-master/quorum state=present regexp="^" line="{{ quorum }}" create=yes
#  replace: dest=/etc/mesos-master/quorum regexp='^' replace='{{ quorum }}'

- name: set hostname in mesos
  lineinfile: dest=/etc/mesos-master/hostname state=present regexp="^" line="{{ inventory_hostname }}" create=yes

- name: set master ip in mesos
  lineinfile: dest=/etc/mesos-master/ip state=present create=yes regexp="^" line="{{ mesos_ip_address }}"

- name: set cluster hostname
  lineinfile: dest=/etc/mesos-master/cluster state=present create=yes regexp="^" line="{{ mesos_clustername }}"

- name: enable cluster authentication
  lineinfile: dest=/etc/mesos-master/authenticate_frameworks state=present create=yes regexp="^" line="true"

- name: enable cluster http readwrite authentication
  lineinfile: dest=/etc/mesos-master/authenticate_http_readwrite state=present create=yes regexp="^" line="true"    

- name: enable cluster http readonly authentication
  lineinfile: dest=/etc/mesos-master/authenticate_http_readonly state=present create=yes regexp="^" line="true"      

- name: enable cluster agent authentication
  lineinfile: dest=/etc/mesos-master/authenticate_agents state=present create=yes regexp="^" line="true"

- name: enable cluster credentials
  lineinfile: dest=/etc/mesos-master/credentials state=present create=yes regexp="^" line="/etc/mesos/credentials"

- name: enable cluster acls
  lineinfile: dest=/etc/mesos-master/acls state=present create=yes regexp="^" line="file:///etc/mesos/acls"

- name: disable hostname lookup
  lineinfile: dest=/etc/mesos-master/hostname_lookup state=present create=yes regexp="^" line="false"

- name: set slave ping timeouts
  lineinfile: dest=/etc/mesos-master/max_agent_ping_timeouts state=present create=yes regexp="^" line="20"

- name: set memory profiling
  lineinfile: dest=/etc/mesos-master/memory_profiling state=present create=yes regexp="^" line="true"

- name: set offer timeout
  lineinfile: dest=/etc/mesos-master/offer_timeout state=present create=yes regexp="^" line="2mins"

- name: set role sorter
  lineinfile: dest=/etc/mesos-master/role_sorter state=present create=yes regexp="^" line="random"

- name: set framework sorter
  lineinfile: dest=/etc/mesos-master/framework_sorter state=present create=yes regexp="^" line="random"

- name: set slave removal rate limit
  lineinfile: dest=/etc/mesos-master/agent_removal_rate_limit state=present create=yes regexp="^" line="100/1mins"

- name: set mesos module directory
  lineinfile: dest=/etc/mesos-master/modules_dir state=present create=yes regexp="^" line="/etc/mesos/modules"

- name: set mesos work-dir
  lineinfile: dest=/etc/mesos-master/work_dir state=present create=yes regexp="^" line="/var/lib/mesos" mode=0755

- name: create mesos module directory
  file:
    path: /etc/mesos/modules
    state: directory
    mode: 0750

- name: copy mesos credentials
  template: src=credentials.j2 dest=/etc/mesos/credentials mode=0640

- name: copy mesos acls
  template: src=acls.j2 dest=/etc/mesos/acls mode=0640  

- name: copy marathon secret
  template: src=marathon.secret.j2 dest=/etc/mesos/marathon.secret mode=0640  

- name: start necessary services
  service:
    name: "{{ item }}"
    enabled: yes
    state: restarted
  with_items:
    - mesos-master
  tags:
    - cert
