---

- name: create mesos_dns group
  group:
    name: av_mesos_dns
    system: yes
    state: present

- name: create mesos_dns user
  user:
    name: av_mesos_dns
    group: av_mesos_dns
    create_home: no
    system: yes
    state: present

- debug:
    var: ansible_os_family

- name: install mesos-dns
  package:
    name:
      - "mesos-dns={{ mesos_dns_version }}"
    state: present
  tags:
    - install

- name: update mesos-dns
  package:
    name:
      - "mesos-dns={{ mesos_dns_version }}"
    state: present
  tags:
    - update
  when: update | bool

- name: Set file permission
  file:
    path: /usr/bin/mesos-dns
    owner: av_mesos_dns
    mode: '0755'

- name: create config dir for mesos-dns
  file:
    path: /etc/mesos-dns
    owner: av_mesos_dns
    state: directory

- name: create mesos-dns config file
  template: 
    src: mesos-dns.json.j2 
    dest: /etc/mesos-dns/config.json 
    owner: av_mesos_dns
    mode: 0640

- name: copy mesos-dns systemd 
  copy: 
    src: mesos-dns.systemd 
    dest: /etc/systemd/system/mesos-dns.service 
    mode: 0644  

- name: reload systemd
  command: systemctl daemon-reload

- name: restart mesos-dns
  service:
    name: "mesos-dns"
    enabled: yes
    state: restarted
  when: restart | bool

- name: start mesos-dns
  service:
    name: "mesos-dns"
    enabled: yes
    state: started
