---

- name: enable zookeeper update
  lineinfile:
    dest: "/etc/yum.conf"
    regexp: "^exclude=mesos*"
    line: '#exclude=mesos* docker* ceph* zookeeper* marathon*'
    state: present
  when:
    ansible_os_family == "RedHat"


- name: install zookeeper packages ubuntu
  package:
    name:
      - openjdk-17-jdk
      - zookeeper
    state: present
  when:
    ansible_os_family == "Debian"

- name: install zookeeper packages centos
  package:
    name:
      - java-1.6.0-openjdk.x86_64
      - zookeeper
    state: present
  when:
    ansible_os_family == "RedHat"

- name: disable zookeeper update
  lineinfile:
    dest: "/etc/yum.conf"
    regexp: "^#exclude=mesos*"
    line: 'exclude=mesos* docker* ceph* zookeeper* marathon*'
    state: present
  when:
    ansible_os_family == "RedHat"

- name: enable zookeeper authentication
  lineinfile: dest=/etc/zookeeper/conf/java.env state=present regexp="^" line="SERVER_JVMFLAGS=\"-Djava.security.auth.login.config=/etc/zookeeper/conf/jaas.conf\"" create=yes

- name: set master ID
  lineinfile: dest=/var/lib/zookeeper/myid state=present regexp="^" line="{{ myid }}" create=yes

- name: remove server line in zookeeper config
  lineinfile:
    dest=/etc/zookeeper/conf/zoo.cfg    
    state=absent
    regexp='^server.' 

- name: add zookeepers to config
  lineinfile:
    dest=/etc/zookeeper/conf/zoo.cfg
    line="{{ item }}"
    state=present
  with_items:
    - "{% for host in groups['manager'] %}server.{{ hostvars[host].myid }}={{ host }}:2888:3888\n{% endfor %}"

- name: add sasl to config
  lineinfile:
    dest=/etc/zookeeper/conf/zoo.cfg
    line="{{ item }}"
    state=present
  with_items:
    - "authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider"
    - "requireClientAuthScheme=sasl"

- name: disable adminServer
  lineinfile:
    dest: /etc/zookeeper/conf/zoo.cfg    
    state: present
    regexp: "^admin.enableServer*" 
    line: "admin.enableServer=false"

- name: copy zookeeper jaas file
  template: src=jaas.conf.j2 dest=/etc/zookeeper/conf/jaas.conf mode=0640  

- name : Start zookeeper server and enable at reboot
  service : name=zookeeper state=restarted enabled=yes


