---

mesos_password: "marathon"
mesos_user: "mesos"
mesos_clustername: "DEFAULT"

libprocess_enable_ssl: "false"
libprocess_enable_ssl_verify: "false"
libprocess_ssl_require_cert: "false"
libprocess_ssl_enable_downgrade: "true"
libprocess_ssl_ciphers: "AES128-SHA:AES256-SHA:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES256-SHA:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256"

mesos_rpm: "mesos-1.11.0-0"
mesos_deb: "aventer-mesos=1.11.0-0.5.0"

mesos_logging_level: "INFO"
mesos_quiet: false

mesos_ssl_key: "../files/mesos.key"
mesos_ssl_crt: "../files/mesos.crt"

mesos_etc_dir: "/etc/mesos-agent"
mesos_logs_dir: "/var/log/mesos"
mesos_work_dir: "/var/lib/mesos"

mesos_ulimit: "16384"
mesos_docker_sock: "/var/run/docker.sock" 

mesos_containerizer_list:
  - docker
  - mesos

mesos_docker_config_enable: false  
mesos_docker_config_path: "/root/.docker/config.json"
mesos_docker_config_json: '{}'

mesos_port_range: "[31000-32000]"

mesos_enable_systemd: "true"

restart: false  
update: false  

libprocess_ssl_hostname_validation_scheme: "openssl"  

mesos_attributes: ""

eth_if: "eth0"
ansible_eth_if: "ansible_{{ eth_if }}"


