---

- name: install required packages
  yum: name={{ item }} state=latest
  with_items:
    - httpd-tools

- name: download prometheus
  get_url: url={{ prometheus_url }} dest=/opt mode=0440

- user: name={{ prometheus_user }} shell=/bin/bash home=/opt/prometheus

- name: unpack prometheus
  unarchive: src=/opt/{{ prometheus_package }} dest=/opt/prometheus copy=no owner={{ prometheus_user }} group={{ prometheus_group }}

- name: copy prometheus.yml config file
  template: src=prometheus.yml.j2 dest=/opt/prometheus/{{ prometheus_archive_contents }}/prometheus.yml mode=0644
  
- name: copy prometheus sysconfig
  copy: src=prometheus_sysconfig dest=/etc/sysconfig/prometheus mode=0644

- name: copy prometheus systemd
  template: src=prometheus_systemd.j2 dest=/etc/systemd/system/prometheus.service mode=0644
  notify: reload systemd

- name: start prometheus
  service: name=prometheus state=started enabled=yes

- name: download alertmanager for prometheus
  get_url: url={{ alertmanager_prometheus_url }} dest=/opt mode=0440

- name: Create alertmanager directory
  file: dest=/opt/prometheus/alertmanager state=directory mode=0755 owner={{ prometheus_user }} group={{ prometheus_group }}

- name: unpack prometheus
  unarchive: src=/opt/{{ alertmanager_prometheus_package }} dest=/opt/prometheus/alertmanager copy=no owner={{ prometheus_user }} group={{ prometheus_group }}

- meta: flush_handlers
