
- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - { role: mesos-master }    

- name: Configure Worker Server
  become: yes
  hosts: worker
  serial: 40%    
  roles:
    - { role: mesos-slave }    
