- name: Install EPEL Repositories on all Servers
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: epel }

- name: Install CHRONY on all Servers
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: chrony }

- name: Install NGINX on ui Servers
  hosts: ui
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: nginx }

- name: Install Consul on mesos-master
  hosts: master
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: consul }

- name: Install DOCKER on all Servers
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: docker }

- name: Install DNSMASQ on all Servers
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: dnsmasq }
