- name: Configure CENTOS
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: centos }

- name: Create admin User
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: add-user }

- name: Install EPEL Repositories on all Servers
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: epel }

- name: Install CHRONY on all Servers
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: chrony }

- name: Install NGINX on ui Servers
  hosts: ui
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: nginx }

- name: Install Consul Server on mesos-master
  hosts: master
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: consul }

## - name: Install Consul Agent on mesos-slave
##   hosts: slave
##   become: true
##   become_user: root
##   become_method: sudo
##   roles:
##     - { role: consul-agent }    

- name: Install DOCKER on all Servers
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: docker }

- name: Install DNSMASQ on all Servers
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: dnsmasq }


- name: Install MESOS on mesos-master
  hosts: master
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: mesos-master }

- name: Install MESOS on mesos-slave
  hosts: slave
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: mesos-slave }

- name: Install WEAVE on mesos-slave
  hosts: slave
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: weave }

- name: Install WEAVESCPOPE on mesos-slave
  hosts: slave
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: weavescope }    

- name: Install REGISTRATOR on mesos-slave
  hosts: slave
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: registrator }

- name: Install MARATHON on ui
  hosts: ui
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: marathon }

#- name: Install MARATHON-LB on mesos-slave
#  hosts: ui
#  become: true
#  become_user: root
#  become_method: sudo
#  roles:
#    - { role: marathon-lb }
    

- name: Install PROMETHEUS on all servers
  hosts: all
  become: true
  become_user: root
  become_method: sudo
  roles:
    - { role: prometheus }    
