- name: gather all hosts information
  hosts: all
  

- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - { role: mesos-dns } 

- name: Configure DNS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    #- { role: dnsmasq }

 
