- name: gather all hosts information
  hosts: all
  
- name: Configure CENTOS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - { role: centos }
    - { role: repos }

- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - role: mesos-dns 
      tags:
        - dns
    - { role: zookeeper }
    - { role: mesos-master }

- name: Configure DNS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - role: dnsmasq
      tags:
        - dns
 
- name: Configure Worker Server
  become: yes
  hosts: worker
  serial: 20%    
  roles:
    - { role: docker }
    - role: weave_plugin_mesos
      tags:
        - weave
    - role: weave
      tags:
        - weave
    - { role: mesos-modules-agent } 
    - { role: mesos-agent }
    - { role: rexray } 
    - { role: weavescope }

- name: Install and Start Frameworks
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - { role: marathon }
    - { role: metronome }


    
