- name: gather all hosts information
  hosts: all
  
- name: Configure CENTOS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - role: centos
      tags:
        - manager
        - worker
    - role: repos
      tags:
        - manager
        - worker

- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - role: mesos-dns 
      tags:
        - dns
        - manager
    - role: zookeeper
      tags:
        - zookeeper
        - manager
    - role: mesos-master
      tags:
        - manager
        - mesos

- name: Configure DNS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - role: dnsmasq
      tags:
        - dns
        - manager
        - worker
 
- name: Configure Worker Server
  become: yes
  hosts: worker
  serial: 20%    
  roles:
    - role: docker
      tags:
        - docker
        - worker
    - role: weave_plugin_mesos
      tags:
        - weave
        - worker
    - role: weave
      tags:
        - weave
        - worker
    - role: mesos-modules-agent
      tags:
        - mesos
        - worker
    - role: mesos-agent
      tags:
        - mesos
        - worker
    - role: rexray
      tags:
        - rexray
        - worker
    - role: weavescope
      tags:
        - weave
        - worker

- name: Install and Start Frameworks
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - role: marathon
      tags:
        - marathon
    - role: metronome
      tags:
        - metronome


    
