- name: gather all hosts information
  hosts: all
  
- name: Configure OS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - role: os
      tags:
        - manager
        - worker
    - role: repos
      tags:
        - manager
        - worker
        - repos

- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 50%
  roles:
    - role: mesos-dns 
      tags:
        - dns
        - manager
    - role: zookeeper
      tags:
        - zookeeper
        - manager
    - role: mesos-master
      tags:
        - manager
        - mesos
        - mesos-manager
    - role: mesos-ssl 
      tags:
        - mesos
        - ssl
      when: libprocess_enable_ssl|bool == True
    - role: docker
      tags:
        - docker
      when: docker|bool == True

- name: Configure DNS
  become: yes
  hosts: all
  roles:
    - role: dnsmasq
      tags:
        - dns
        - manager
        - worker
    - role: hosts
      tags:
        - dns
        - manager
        - worker
        - hosts
 
- name: Configure Worker Server
  become: yes
  hosts: worker
  serial: 40%    
  roles:
    - role: mesos-agent
      tags:
        - mesos
        - mesos-agent
        - worker
    - role: docker
      tags:
        - docker
        - worker
    - role: weave
      tags:
        - weave
        - worker
    - role: mesos-ssl 
      tags:
        - mesos
        - ssl
      when: libprocess_enable_ssl|bool == True
    - role: weave_plugin_mesos
      tags:
        - weave
        - plugin
        - worker
    - role: weavescope
      tags:
        - weave
        - worker

- name: Install and Start Frameworks
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - role: marathon
      when:
        ansible_os_family == "RedHat"
      tags:
        - marathon
    - role: marathon-ssl 
      tags:
        - marathon
        - ssl
      when: libprocess_enable_ssl|bool == True and ansible_os_family == "RedHat"

