- name: gather all hosts information
  hosts: all
  
- name: Configure CENTOS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - { role: centos }
    - { role: epel }  


- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 20%
  roles:
    - { role: consul }
    - { role: mesos-master }
    - { role: prometheus-node-exporter }

- name: Configure DNS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - { role: dnsmasq }

 
- name: Configure Worker Server
  become: yes
  hosts: 
    - worker
  serial: 20%    
  roles:
    #- { role: rexray } 
    - { role: consul-agent }
    - { role: docker }    
    - { role: weave }
    - { role: mesos-slave }    
    - { role: rexray_s3fs_plugin } 
    - { role: weavescope }    
    - { role: weaveexpose }    
    - { role: registrator }         
    - { role: cadvisor }    

- name: Start marathon
  become: yes
  hosts: manager
  serial: 20%
  roles:
    - { role: marathon }        
  
- name: Install PROMETHEUS on all servers
  become: yes
  hosts: prometheus
  roles:
    - { role: prometheus }

- name: Install PROMETHEUS haproxy-exporter on haproxy server
  become: yes
  hosts: haproxy
  roles:
    - { role: prometheus-haproxy-exporter } 

   
#- name: Configure Graylog
#  hosts: graylog
#  roles:
#    - { role: elasticsearch }
#    - { role: mongodb }    
#    - { role: graylog }    

    
