- name: gather all hosts information
  hosts: all
  
- name: Configure CENTOS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - { role: centos }
    - { role: repos }

- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - { role: consul }
    - { role: mesos-dns }
    - { role: zookeeper }
    - { role: mesos-master }        

- name: Configure DNS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - { role: dnsmasq }
 
- name: Configure Worker Server
  become: yes
  hosts: worker
  serial: 20%    
  roles:
    - { role: consul-agent }
    - { role: docker }    
    - { role: weave_plugin_mesos }
    - { role: weave }
    - { role: mesos-modules-slave } 
    - { role: mesos-slave }    
    - { role: rexray_s3fs_plugin } 
    - { role: weavescope }    

- name: Start Frameworks
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - { role: marathon }
    - { role: metronome }
  
- name: Install PROMETHEUS and Grafana
  become: yes
  hosts: grafana
  roles:
    - { role: prometheus }
    - { role: grafana }

- name: Install PROMETHEUS node-exporter on all servers
  become: yes
  hosts: 
    - manager
    - worker
    - vpn
    - grafana
    - legacy
  roles:     
    - { role: prometheus-node-exporter }
   
- name: Configure Graylog
  hosts: graylog
  roles:
    - { role: elasticsearch }
    - { role: mongodb }    
    - { role: graylog }    
   
- name: Init Jobs
  hosts: worker
  roles:
    - { role: cadvisor }
    - { role: registrator }    
  


    
