- name: gather all hosts information
  hosts: all
  
- name: Configure CENTOS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - { role: centos }
    - { role: repos }

- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 20%
  roles:
    - { role: consul }
    - { role: mesos-master }    

- name: Configure DNS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - { role: dnsmasq }

 
- name: Configure Worker Server
  become: yes
  hosts: worker
  serial: 30%    
  roles:
    - { role: chronos }
    - { role: consul-agent }
    - { role: docker }    
    - { role: weave }
    - { role: mesos-slave }    
    - { role: rexray_s3fs_plugin } 
    - { role: weavescope }    
    - { role: weave_plugin_mesos }    
    - { role: registrator }         
    - { role: cadvisor }    

- name: Start marathon
  become: yes
  hosts: manager
  serial: 20%
  roles:
    - { role: marathon }        
  
- name: Install PROMETHEUS and Grafana
  become: yes
  hosts: grafana
  roles:
    - { role: prometheus }
    - { role: grafana }

- name: Install PROMETHEUS node-exporter on all servers
  become: yes
  hosts: 
    - manager
    - worker
    - vpn
    - grafana
    - legacy
  roles:     
    - { role: prometheus-node-exporter }
   
- name: Configure Graylog
  hosts: graylog
  roles:
    - { role: elasticsearch }
    - { role: mongodb }    
    - { role: graylog }    


    
