- name: gather all hosts information
  hosts: all
  
- name: Configure CENTOS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - { role: centos }
    - { role: repos }

- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - { role: mesos-dns }    
    - { role: zookeeper }
    - { role: mesos-master }        

- name: Configure DNS
  become: yes
  hosts: 
    - manager
    - worker
  roles:
    - { role: dnsmasq }
 
- name: Configure Worker Server
  become: yes
  hosts: worker
  serial: 20%    
  roles:
    - { role: docker }    
    - { role: weave_plugin_mesos }
    - { role: weave }
    - { role: mesos-modules-slave } 
    - { role: mesos-slave }    
    - { role: rexray } 
    - { role: weavescope }    

- name: Install and Start Frameworks
  become: yes
  hosts: manager
  serial: 40%
  roles:
    - { role: marathon }
    - { role: metronome }


    
