- name: gather all hosts information
  hosts: all

- name: Precheck
  become: yes
  serial: 100%
  hosts: all
  roles:
    - role: precheck
      tags:
        - precheck
        - worker

- name: Configure OS
  become: yes
  serial: 100%
  hosts: 
    - manager
    - worker
  roles:
    - role: os
      tags:
        - manager
        - worker
        - os
    - role: repos
      tags:
        - manager
        - worker
        - repos

- name: Configure Zookeeper Server
  become: yes
  hosts: zookeeper
  serial: 50%
  roles:
    - role: zookeeper
      tags:
        - zookeeper

- name: Configure Manager Server
  become: yes
  hosts: manager
  serial: 50%
  roles:
    - role: mesos-dns 
      tags:
        - dns
        - manager
    - role: mesos-master
      tags:
        - manager
        - mesos
        - mesos-manager
    - role: mesos-ssl 
      tags:
        - mesos
        - ssl
      when: libprocess_enable_ssl|bool == True
    - role: docker
      tags:
        - docker
      when: docker|bool == True
    - role: docker-cron
      tags:
        - docker
        - cron
      when: docker|bool == True

- name: Configure DNS
  become: yes
  hosts: all
  serial: 100%    
  roles:
    - role: dnsmasq
      tags:
        - dns
        - manager
        - worker
    - role: hosts
      tags:
        - dns
        - manager
        - worker
        - hosts
 
- name: Configure Worker Server
  become: yes
  hosts: worker
  serial: 100%    
  roles:
    - role: mesos-agent
      tags:
        - mesos
        - mesos-agent
        - worker
    - role: docker
      tags:
        - docker
        - worker
    - role: mesos-ssl 
      tags:
        - mesos
        - ssl
      when: libprocess_enable_ssl|bool == True
    - role: cni_plugin_mesos
      tags:
        - worker
        - cni

