---

- name: deactivate selinux permanent
  lineinfile:
    dest: /etc/sysconfig/selinux
    regexp: ^SELINUX=
    line: SELINUX=disabled
    state: present
    create: yes

- name: deactivate selinux temp
  command: setenforce 0
  ignore_errors: true