---

- name: deactivate selinux permanent
  sudo: yes
  lineinfile:
    dest: /etc/sysconfig/selinux
    regexp: ^SELINUX=
    line: SELINUX='disabled'
    state: present
    create: yes

- name: deactivate selinux without reboot
  shell: setenforce 0