---

- name: deactivate selinux permanent
  lineinfile:
    dest: /etc/sysconfig/selinux
    regexp: ^SELINUX=
    line: SELINUX=disabled
    state: present
    create: yes

- name: deactivate selinux temp
  command: setenforce 0
  ignore_errors: true

- name: disable firewalld
  command: systemctl disable firewalld
  ignore_errors: true

- name: stop firewalld
  command: systemctl stop firewalld
  ignore_errors: true    
