---

- name: Check cgroups version
  stat:
    path: /sys/fs/cgroup/cpu 
  register: cg_result

- name: Raise failure if cgroups v2 is enable  
  fail:
    msg: "Please enable CGroups Version 1 (/etc/default/grub; GRUB_CMDLINE_LINUX=' systemd.unified_cgroup_hierarchy=0 ')"
  when: not cg_result.stat.exists


    

