---
  - name: install chronos
    package:
      name: chronos-2.5.1
      state: installed
      update_cache: yes

  - name: start chronos running
    service:
      name: chronos
      enabled: yes
      state: stopped
