---

- name: install marathon packages
  yum:
    name:
      - marathon-1.10.17
    state: installed

- name: create vault plugin directory for marathon
  file:
    path: /etc/marathon/plugins
    state: directory

- name: get vault plugin for marathon 
  get_url: url={{ marathon_vault_url }} dest=/etc/marathon/plugins/ mode=0440

- name: untar vault plugin for marathon
  shell: "tar -C /etc/marathon/plugins/ -xvf /etc/marathon/plugins/*.tar"

- name: remove plugin tar file
  shell: "rm /etc/marathon/plugins/*.tar"

- name: copy vault plugin config
  template: src=plugin-conf.json.j2 dest=/etc/marathon/plugins-conf.json mode=0644
 
- name: Delete old marathon config
  file: path=/etc/sysconfig/marathon state=absent  

- name: configure mesos master nodes
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^zk" line="MARATHON_MASTER=zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: configure mesos master nodes
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^zk" line="MARATHON_ZK=zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/marathon"

- name: set hostname in marathon
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_HOSTNAME={{ ansible_fqdn }}" create=yes
  
- name: enable mesos authenticaton
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_AUTHENTICATION=" create=yes

- name: enable mesos principal
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_AUTHENTICATION_PRINCIPAL={{ mesos.user }}" create=yes

- name: enable mesos secret file
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_AUTHENTICATION_SECRET_FILE=/etc/mesos/marathon.secret" create=yes

- name: enable mesos role
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_ROLE=marathon" create=yes

- name: enable mesos user
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_USER=root" create=yes

- name: enable basic authentication
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_HTTP_CREDENTIALS={{ marathon_basic_auth }}" create=yes

- name: change java opts of marathon
  lineinfile: dest=/etc/sysconfig/marathon state=present line="JAVA_OPTS=-XX:MaxDirectMemorySize=1G" create=yes

- name: enable vault plugin
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_ENABLE_FEATURES=secrets,external_volumes,vips,task_killing,gpu_resources" create=yes

- name: enable ssl for mesos libprocess
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^LIBPROCESS_SSL_ENABLED=*" line="LIBPROCESS_SSL_ENABLED={{ libprocess_enable_ssl }}"  

- name: enable ssl verify for mesos libprocess
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^LIBPROCESS_SSL_VERIFY_CERT=*" line="LIBPROCESS_SSL_VERIFY_CERT={{ libprocess_enable_ssl_verify }}"  

- name: add mesos libprocess ssl key file
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^LIBPROCESS_SSL_KEY_FILE=*" line="LIBPROCESS_SSL_KEY_FILE=/etc/mesos/ssl/mesos.key" 

- name: add mesos libprocess ssl cert file
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^LIBPROCESS_SSL_CERT_FILE=*" line="LIBPROCESS_SSL_CERT_FILE=/etc/mesos/ssl/mesos.crt" 

- name: enable required ssl cert
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^LIBPROCESS_SSL_REQUIRE_CERT=*" line="LIBPROCESS_SSL_REQUIRE_CERT={{ libprocess_ssl_require_cert }}" 

- name: set mesos libprocess ssl downgrade
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^LIBPROCESS_SSL_ENABLE_DOWNGRADE=*" line="LIBPROCESS_SSL_ENABLE_DOWNGRADE={{ libprocess_ssl_enable_downgrade }}" 

- name: set ssl keystore file
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^MARATHON_SSL_KEYSTORE_PATH=*" line="MARATHON_SSL_KEYSTORE_PATH=/etc/mesos/ssl/marathon.jks" 

- name: set ssl keystore password
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^MARATHON_SSL_KEYSTORE_PASSWORD=*" line="MARATHON_SSL_KEYSTORE_PASSWORD={{ marathon_jks_password }}" 

- name: Change group owner of secret file
  file:
    path: /etc/mesos/marathon.secret
    owner: root
    group: marathon

- name: add ssl keystore
  copy:
    src: "{{ marathon_ssl_jks }}"
    dest: /etc/mesos/ssl/marathon.jks
    owner: root
    group: marathon  
    mode: 0640  
  tags:
    - cert

- name: symlink marathon
  file: 
    src: /usr/share/marathon/bin/marathon
    dest: /usr/bin/marathon
    state: link

- name: copy marathon systemd 
  copy: src=marathon.systemd dest=/etc/systemd/system/marathon.service mode=0644  

- name: reload systemd
  command: systemctl daemon-reload

- name: start marathon
  service:
    name: "marathon"
    enabled: yes
    state: restarted
  tags:
    - cert
