---

- name: install marathon packages
  yum: name={{ item }} state=latest
  with_items:
    - marathon

- name: Delete old marathon config
  file: path=/etc/sysconfig/marathon state=absent

- name: configure mesos master nodes
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^zk" line="MARATHON_MASTER=zk://{% for host in groups['master'] %}{{ hostvars[host].client_address }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: configure mesos master nodes
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^zk" line="MARATHON_ZK=zk://{% for host in groups['master'] %}{{ hostvars[host].client_address }}:2181{% if not loop.last %},{% endif %}{% endfor %}/marathon"

- name: set hostname in marathon
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_HOSTNAME={{ ansible_fqdn }}" create=yes
  
- name: enable mesos authenticaton
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_AUTHENTICATION=" create=yes

- name: enable mesos principal
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_AUTHENTICATION_PRINCIPAL=marathon" create=yes

- name: enable mesos secret file
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_AUTHENTICATION_SECRET_FILE=/etc/mesos/marathon.secret" create=yes

- name: enable mesos role
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_ROLE=marathon" create=yes

- name: enable basic authentication
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_HTTP_CREDENTIALS={{ marathon_basic_auth }}" create=yes

- name: copy marathon systemd 
  copy: src=marathon.systemd dest=/etc/systemd/system/marathon.service mode=0644  

- name: reload systemd
  command: systemctl daemon-reload

- name: start marathon
  service:
    name: "marathon"
    enabled: yes
    state: started
