---

- name: install marathon packages
  yum:
    name:
      - marathon-1.8.218
    state: installed

- name: create vault plugin directory for marathon
  file:
    path: /etc/marathon/plugins
    state: directory

- name: get vault plugin for marathon 
  get_url: url={{ marathon_vault_url }} dest=/etc/marathon/plugins/ mode=0440

- name: untar vault plugin for marathon
  shell: "tar -C /etc/marathon/plugins/ -xvf /etc/marathon/plugins/*.tar"

- name: remove plugin tar file
  shell: "rm /etc/marathon/plugins/*.tar"

- name: copy vault plugin config
  template: src=plugin-conf.json.j2 dest=/etc/marathon/plugins-conf.json mode=0644
 
- name: Delete old marathon config
  file: path=/etc/sysconfig/marathon state=absent  

- name: configure mesos master nodes
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^zk" line="MARATHON_MASTER=zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/mesos"

- name: configure mesos master nodes
  lineinfile: dest=/etc/sysconfig/marathon create=yes state=present regexp="^zk" line="MARATHON_ZK=zk://client:{{ zookeeper_client_secret }}@{% for host in groups['manager'] %}{{ host }}:2181{% if not loop.last %},{% endif %}{% endfor %}/marathon"

- name: set hostname in marathon
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_HOSTNAME={{ ansible_fqdn }}" create=yes
  
- name: enable mesos authenticaton
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_AUTHENTICATION=" create=yes

- name: enable mesos principal
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_AUTHENTICATION_PRINCIPAL=marathon" create=yes

- name: enable mesos secret file
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_AUTHENTICATION_SECRET_FILE=/etc/mesos/marathon.secret" create=yes

- name: enable mesos role
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_ROLE=marathon" create=yes

- name: enable mesos user
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_MESOS_USER=root" create=yes

- name: enable basic authentication
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_HTTP_CREDENTIALS={{ marathon_basic_auth }}" create=yes

- name: change java opts of marathon
  lineinfile: dest=/etc/sysconfig/marathon state=present line="JAVA_OPTS=-XX:MaxDirectMemorySize=1G" create=yes

- name: enable vault plugin
  lineinfile: dest=/etc/sysconfig/marathon state=present line="MARATHON_ENABLE_FEATURES=secrets,external_volumes,vips,task_killing,gpu_resources" create=yes

- name: Change group owner of secret file
  file:
    path: /etc/mesos/marathon.secret
    owner: root
    group: av_marathon

- name: symlink marathon
  file: 
    src: /usr/share/marathon/bin/marathon
    dest: /usr/bin/marathon
    state: link

- name: copy marathon systemd 
  copy: src=marathon.systemd dest=/etc/systemd/system/marathon.service mode=0644  

- name: create marathon group
  group:
    name: av_marathon
    gid: 986
    system: yes
    state: present

- name: create marathon user
  user:
    name: av_marathon
    uid: 986
    group: av_marathon
    create_home: no
    system: yes
    state: present

- name: reload systemd
  command: systemctl daemon-reload

- name: start marathon
  service:
    name: "marathon"
    enabled: yes
    state: restarted
